# Generated by Django 5.0.3 on 2024-05-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_for', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_home.roomfor'),
        ),
    ]
