# Generated by Django 5.0.3 on 2024-05-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_home', '0003_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
