# Generated by Django 5.0.4 on 2024-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_home', '0004_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='lat_bath',
            field=models.CharField(default='attached/separate', max_length=200),
        ),
    ]
